### ISSUE TITLE
Zoom behavior broken

### ISSUE THREAD

**Issue by ayushnirwal** [swissspidy/web-stories-wp#13222] opened 2023-04-19 05:10 UTC
## Bug Description

On a 2K display, going from `Fill` or `200%` zoom level (with some non-zero scroll) to `100%` leaves the Display layer and frames layer un aligned. 

## Expected Behaviour

The Display Layer should not be out of view.

## Steps to Reproduce

1. Add a few elements to the story.
2. Set the zoom level to 200% or Fill.
3. Scroll to the bottom of the canvas.
4. Set the zoom level to 100% or Fill.
## Screenshots

https://user-images.githubusercontent.com/53055971/232972445-c829b06b-edb5-4ef1-a6f7-c814ea761709.mov

## Additional Context

- Plugin Version: 1.32.0-alpha.0
- WordPress Version: 6.2
- Operating System: MacOS
- Browser: Chrome
- Display resolution: 2048 * 1080

**Comment by swissspidy** [comment] 2023-04-25 11:40
Good catch! We should fix this

**Comment by swissspidy** [comment] 2023-05-02 09:04
Possibly related: #7638

**Comment by swissspidy** [comment] 2023-11-08 14:05
@AnuragVasanwala are you able to reproduce this one?

**Comment by AnuragVasanwala** [comment] 2023-11-09 04:54
> @AnuragVasanwala are you able to reproduce this one?

@swissspidy Yes, I tried to reproduce it and Display Layer gets out of the view. Upon adding a new element gets back Display Layer so need fix for this. Will identify the cause.

Do you suggest any pointers regarding the issue?

**Comment by AnuragVasanwala** [comment] 2023-11-20 12:43
@swissspidy Just an update!

Changing `false` value of `--overflow-y` to `auto` (from `visible`) seems fixed the issue but still trying to figure out why? 🤔 

https://github.com/GoogleForCreators/web-stories-wp/blob/53b1b9ee359e6e9eab09428d87513907ce020667/packages/story-editor/src/components/canvas/layout.js#L361

```diff
- '--overflow-y': hasVerticalOverflow ? 'scroll' : 'visible', 
+ '--overflow-y': hasVerticalOverflow ? 'scroll' : 'auto', 
```

**Closed as completed** 2024-03-26 13:05 UTC
Labels: Type: Bug, Group: Canvas, P3
