### ISSUE TITLE
Linear Image Style Filter not working

### ISSUE THREAD

**Issue by joelmu** [swissspidy/web-stories-wp#13041] opened 2023-02-17 09:40 UTC
## Bug Description

Linear filter not appearing on images. Other filters work. The overlay element gets as an example: `background-image: linear-gradient(.5 turn ,rgba(0,0,0,0) 0%,rgba(0,0,0,.8) 100%);` css style and it seems like just removing the space between .5 and turn makes it work: `background-image: linear-gradient(.5turn ,rgba(0,0,0,0) 0%,rgba(0,0,0,.8) 100%);`.

## Expected Behaviour

Linear filter should appear images with correct css. 

## Steps to Reproduce

Add image to a story and add linear filter to it. Then save the story and view it. Inspect story to see the invalid css on the element.

## Screenshots

Video to demonstrate how the linear filter does not work but other do
https://drive.google.com/file/d/1Jw6musrY3_30uIOIZtFPnC0EcEFGd3vS/view?usp=sharing

## Additional Context

- Plugin Version: 1.29.0
- WordPress Version: 6.1.1
- Operating System: macOS 13.1
- Browser: Chrome, Safari, Firefox

**Comment by swissspidy** [comment] 2023-02-17 09:49
Duplicate of #13013 

This will be fixed in the next release

**Closed as not planned by swissspidy** 2023-02-17 09:49 UTC
Labels: Type: Bug
