### ISSUE TITLE
Consider providing the ability to name layers

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10969] opened 2022-03-17 17:51 UTC
## Feature Description

Consider the ability to provide a custom name on layers so that creators are quickly able to name & identify layers on a story page.

This would require UI updates to provide the ability for creators to add and/or update layer names.

**Comment by swissspidy** [comment] 2022-03-18 12:59
Duplicate of #9248

**Closed as completed by swissspidy** 2022-03-18 12:59 UTC
Labels: Type: Enhancement, Group: Canvas
