### ISSUE TITLE
On the Publish modal, when user expands "Author" and then clicks on "Publish" to select date and time, Publish dropdown closes

### ISSUE THREAD

**Issue by felipebochehin87** [swissspidy/web-stories-wp#11841] opened 2022-06-29 12:10 UTC
## Bug Description

On the Publish modal, when user expands "Author" and then clicks on "Publish" to select date and time, Publish dropdown closes, forcing the user to click again so that they can select date and time to publish.

## Expected Behaviour

Publish dropdown must remain open when user clicks on it.

## Steps to Reproduce

1. Add a new story
2. Click on Publish
3. On "Publishing", click on "Author" field
4. Click on Publish field to select date and time - here the dropdown will open and close, forcing the user to click on it again

## Screenshots

https://images.zenhubusercontent.com/235435637/2d24df8f-fcde-406c-ade9-26930c69cdea/2022_06_29_09_01_20.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment] 2022-06-29 12:13
Seems like a duplicate of #11840 because these are all using the same dropdown component.

cc @sblinde

**Comment by sblinde** [comment] 2022-06-29 14:07
Thanks for reporting @felipebochehin87 !
Very well may be the case @swissspidy, I'll pull one of these into our sprint so we can investigate. Thanks!

**Comment by swissspidy** [comment] 2022-07-06 09:23
Closing in favor of #11840

**Closed as completed by swissspidy** 2022-07-06 09:23 UTC
Labels: Type: Bug, Group: Design System
