### ISSUE TITLE
Consider providing the ability for creators to lock layers

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10970] opened 2022-03-17 17:53 UTC
## Feature Description

Consider providing the ability to creators to lock layers, so that a locked layer is unable to be edited until the layer has been explicity unlocked

This would require UI updates to the layers panel to show each layer's lock status. Clicking on this lock state would toggle the state to the opposite of its current (locked/unlocked)

**Comment by swissspidy** [comment] 2022-03-17 22:32
Duplicate of #7332

**Closed as completed by swissspidy** 2022-03-17 22:32 UTC
Labels: Type: Enhancement, Group: Canvas
