### ISSUE TITLE
Resizing a text box moves it vertically

### ISSUE THREAD

**Issue by jortega-consultant** [swissspidy/web-stories-wp#13157] opened 2023-03-22 22:55 UTC
## Bug Description

When a user is resizing a text box the anchor position of the text should not shift up or down on the canvas as the box is resized.

## Expected Behaviour

When resizing the text box, it should not move vertically on the page, and should maintain its position in relation to the top.

## Steps to Reproduce

- Insert a text box
- Write some text in it
- Resize it from one side
- The textbox moves vertically

## Screenshots

https://user-images.githubusercontent.com/111754166/227056017-33a63726-7349-48c5-965c-10688c9ea374.mov

## Additional Context

- Plugin Version: 1.27.0
- WordPress Version: 
- Operating System:
- Browser:

**Comment by swissspidy** [comment] 2023-03-23 10:11
This looks like a duplicate of #11380, so I'll close this one in favor of the existing issue.

While I understand the existing behavior can be confusing for some, it might be confusing for others if we changed such a crucial interaction after such a long time. Because of this, I can't give you a guarantee on if and when we are going to address this. But please watch #11380 for any updates.

PS. You should really update the plugin to the latest version!

**Closed as not planned by swissspidy** 2023-03-23 10:11 UTC
Labels: Type: Bug, Status: Duplicate, Elements: Text
