### ISSUE TITLE
Text: Line Wraps in Chrome and Firefox when applying Fill Mode

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#11190] opened 2022-04-05 14:06 UTC
## Bug Description
A user reported Text has unexpected line wraps when previewing it. The issue does not occur in Safari for [this user's story](https://holidaystoswitzerland.com/web-stories/things-to-do-in-montreux-and-vevey/), but it does occur in Chrome & Firefox.

When I tested with [this story](https://testsite.cmsdevrel.com/web-stories/1007/), the text with Fill applied does not display correctly in any browser.

## Expected Behaviour

Text should not wrap unexpectedly and should display the same in both preview and editor. 

## Steps to Reproduce

1. Create story
2. Add Text Title 1 with a few more words
3. Apply fill mode
4. Preview story
5. Note missing text 

## Screenshots

Editor
<img width="731" alt="Screen Shot 2022-04-05 at 10 01 02 AM" src="https://user-images.githubusercontent.com/66372350/161772164-94d98e34-2f51-45e3-9d39-46a7444f4cd2.png">

Preview
<img width="652" alt="Screen Shot 2022-04-05 at 10 01 07 AM" src="https://user-images.githubusercontent.com/66372350/161772082-347660af-72bb-47bf-af92-77d05a62a1f3.png">

User's story in chrome
<img width="573" alt="Screen Shot 2022-04-05 at 9 59 21 AM" src="https://user-images.githubusercontent.com/66372350/161772238-5c28ecee-e301-4afd-b1d7-5970e78d0b66.png">

User's story in Safari
<img width="664" alt="Screen Shot 2022-04-05 at 10 01 18 AM" src="https://user-images.githubusercontent.com/66372350/161772283-99d98902-6968-4fd5-8c2d-effec6925896.png">

## Additional Context

- Plugin Version: 1.19.0
- WordPress Version:
- Operating System: macOS
- Browser:

**Comment by swissspidy** [comment] 2022-04-05 14:15
Is this a duplicate of #10973?

**Comment by LuckynaSan** [comment] 2022-04-05 14:24
That issue was reported for mobile devices, but now it seems it occurs on any device. Would you like me to close out #10973 ?

**Comment by swissspidy** [comment] 2022-04-05 14:29
Let's close this one as it's newer; and copy over screenshots from here to the existing issue

**Closed as completed** 2022-04-12 18:41 UTC
Labels: Type: Bug, Elements: Text
