### ISSUE TITLE
Post Lock e2e Test Failure

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10935] opened 2022-03-16 05:33 UTC
`Post Locking › should be able to open the dashboard with locked story` e2e test is failing 

https://github.com/GoogleForCreators/web-stories-wp/runs/5562138494?check_suite_focus=true#step:9:9

![Screen Shot 2022-03-15 at 10.32.34 PM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/2c164568-2c5d-4505-846a-191e5b4c1895)

**Comment by swissspidy** [comment] 2022-03-16 07:58
Duplicate of #10897

**Closed as completed by swissspidy** 2022-03-16 07:58 UTC
Labels: Type: Bug, Type: Infrastructure
