### ISSUE TITLE
Determine a safe location for the combo quick & canvas action menus

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9812] opened 2021-11-24 19:11 UTC
## Feature Description
Originally reported by @agingoldseco 
> If scrollbar gets in the way, we should decide on a set spot for the combined quick action and canvas action menus in the corner that looks best

**Comment by miina** [comment] 2021-11-26 10:51
Duplicate of #9808 as that issue should generally improve the UX of the combo menu.

**Closed as completed by miina** 2021-11-26 10:51 UTC
Labels: Type: Enhancement, UX Needed, Group: Quick Action Menu
