### ISSUE TITLE
Story Locking: missing information on dashboard depending on role

### ISSUE THREAD

**Issue by kkalarickal** [swissspidy/web-stories-wp#12604] opened 2022-11-01 19:20 UTC
## Bug Description

When a web story is being edited by user-A, it appears with a lock icon and a thumbnail of the user-A when viewed in the dashboard by user-B. While testing the `main branch` for 1.27 bug bash, I see that the lock icon and thumbnail is NOT visible depending on the user profile of the entity logged into the wp-admin.

## Expected Behaviour

Irrespective of the profile of the user who is logged in, the lock icon and thumbnail should appear consistently.

## Steps to Reproduce

1. Create an Admin, Editor and Author user profile within the WP instance
2. Login on separate/independent browser sessions as each and open/edit a webstory within the GWS plugin.
3. Now, create and login to another admin user profile on a separate browser instance.
4. If you go to the dashboard, you will see that the three stories opened in step 2, will be represented as "locked" - with the lock icon and the thumbnail for admin/editor/author visible![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/b2ccf69b-e466-465c-a8e4-909e4470fda8)
5. Now create and login as another editor user profile on a separate browser instance.
6. If you go to the dashboard, you will see that one or more of the entries for the different web stories are NOT showing either locked icon or thumbnail or neither.![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/e5538541-bd76-46ec-b6ed-5f9d8a48d1e0)
7. If you repeat the steps 5 & 6 with a new author user profile, there might be a dashboard without any indication that the stories are locked by different user profiles![image.png](https://images.zenhubusercontent.com/5fc17739d77478a91f8d75e3/d28619ff-2f37-4205-882a-26fb7767c84e)

## Additional Context

- Plugin Version: 1.27.0-alpha.0+36c4510
- WordPress Version: WP 6.0
- Operating System: win10
- Browser: Chrome

**Comment by swissspidy** [comment] 2022-11-01 19:36
Essentially looks like a duplicate of #12441

**Comment by spacedmonkey** [comment] 2022-11-02 10:55
I have pushed a fix for this as part of - https://github.com/GoogleForCreators/web-stories-wp/pull/12559.

**Comment by swissspidy** [comment] 2022-11-02 11:18
Awesome, thanks @spacedmonkey!

FYI @kkalarickal

**Comment by swissspidy** [comment] 2022-11-03 13:06
Fixed  #12559.

**Closed as completed by swissspidy** 2022-11-03 13:06 UTC
Labels: Type: Bug, Group: Dashboard, Package: Dashboard, Group: Story Locking, Package: WP Dashboard
