### ISSUE TITLE
Cannot remove a link from a background image after it's been auto-set to a page background image

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10722] opened 2022-02-25 16:17 UTC
## Bug Description
Originally reported by @samwhale 

Cannot remove a link from an image when it is set as the background image. This probably existed before this change was made.

## Steps to Reproduce

1. Place an image element on the canvas
2. Select the image to access the associated design panel
3. Use the link field to enter and attach a link to this image
4. Resize the image to cover the majority of the canvas, triggering the auto-set image as background images

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by miina** [comment] 2022-02-28 09:23
Closing as duplicate of #10701

**Closed as completed by miina** 2022-02-28 09:23 UTC
Labels: Type: Bug, Status: Duplicate, Elements: Image
