### ISSUE TITLE
Editor crashes when uploading/inserting media

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#12804] opened 2022-12-12 16:10 UTC
## Bug Description

While creating my holiday dog food story, I repeatedly had issues with the editor crashing after uploading and inserting an image into the story.

This happened more than four times for me, each time I was presented with a screen similar to this:

![Screen Shot 2022-12-12 at 9.16.28 AM.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/1435d092-e8e4-46a5-afb0-d9160a34efb7)

The story was authored in our Staging site - https://stories-new-wordpress-amp.pantheonsite.io/web-stories/holiday-dog-food-story-b-matt-3/

## Steps to Reproduce

1. Upload a story using the editor Insert -> Upload function
2. Following the successful upload, use the "Insert into Story" button

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment] 2022-12-12 16:41
I was about to file this myself as well :-)

Running into it, too, and some users in support also.

**Comment by miina** [comment] 2022-12-12 18:20
This seems to be a dupe of #12784, no?

Are you looking into this, @swissspidy?

**Comment by swissspidy** [comment] 2022-12-12 18:26
Ah yes we can de-dupe. Let's continue discussion there.

And no, not looking into it right now. Will leave a comment at #12784 with what I've found so far though

**Closed as not planned by swissspidy** 2022-12-12 18:26 UTC
Labels: Type: Bug, Group: Media, P1, Elements: Image
