### ISSUE TITLE
Pausing story does not stop background audio

### ISSUE THREAD

**Issue by sudip-md** [swissspidy/web-stories-wp#10464] opened 2022-02-04 08:07 UTC
## Bug Description

If story have mp3 and user pause the story then music should be stop

## Expected Behaviour

If user pause the story mp3 music should be stop

## Steps to Reproduce

- Add mp3 music, title on story
- Publish it
- Pause the story on front end side

## Screenshots

Video - https://www.awesomescreenshot.com/video/6128501?key=b7d7a2c030997cb9549850e7268b75f4

## Additional Context

- Plugin Version: 1.16.0
- WordPress Version: WP 5.9
- Operating System: Mac OS
- Browser: Chrome (Version 97.0.4692.99 )

**Comment by swissspidy** [comment] 2022-02-04 10:05
Hi there, thanks for filing this.

As far as I know, this is intended behavior. The play/pause button stops any media on the current page and stops the page from advancing to the next page. However, global story-level background audio is unaffected by this and cannot be paused. It can only be muted using the mute button.

If you want to be able to pause/stop the story background audio, you'd need to file this as a bug/enhancement on the https://github.com/ampproject/amphtml repository, which is where the Web Stories format itself is being developed and where this would need to be changed.

I am therefore closing this issue, but please do not hesitate to reach out if there's anything else we can help with.

**Closed as completed by swissspidy** 2022-02-04 10:05 UTC
Labels: Type: Bug, AMP Output, Type: External Issue
