### ISSUE TITLE
Consider providing the ability to group layers

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#10971] opened 2022-03-17 17:56 UTC
## Feature Description

Consider providing creators with the ability to select and group layers, and update the layers panel to show any groupings that have been made by them. 

This would require UI updates to the layers panel to show current grouping hierarchy.

**Comment by swissspidy** [comment] 2022-03-18 12:59
Duplicate of #9244

**Closed as completed by swissspidy** 2022-03-18 12:59 UTC
Labels: Type: Enhancement, Group: Canvas
