### ISSUE TITLE
TypeScript: Convert `wp-story-editor` package

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/web-stories-wp#12238] opened 2022-09-06 18:27 UTC
https://www.npmjs.com/package/wp-types could be useful for typing REST API responses.

**Comment by swissspidy** [comment] 2022-10-21 20:33
@spacedmonkey Just a heads up that this is still blocked by a few other tickets (mainly converting core story-editor types themselves), so it won't be easily possible to finish this just yet. Which is why this wasn't actually in the sprint yet.

**Comment by spacedmonkey** [comment] 2023-01-30 13:55
Marked as blocked by design system type script conversion.

**Closed as not planned** 2023-06-21 09:22 UTC
Labels: Type: Code Quality, P3, Package: WP Story Editor
