### ISSUE TITLE
Quick Actions: Replacing video changes height and width

### ISSUE THREAD

**Issue by spacedmonkey** [swissspidy/web-stories-wp#10721] opened 2022-02-25 14:17 UTC
## Bug Description

When replacing video with another video with different dimensions, the video is cut off and this can not be fixed. 

Found while testing https://github.com/GoogleForCreators/web-stories-wp/pull/10720

## Screenshots

https://user-images.githubusercontent.com/237508/155740864-fe59edfc-a1f0-4c7e-ab5c-b3b4a734c468.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment] 2022-02-25 14:49
Can you upload the video again?

**Comment by spacedmonkey** [comment] 2022-03-02 17:32
After talking about this ticket in sprint planning, we wonder if this is a feature or a bug. Can you take a look @aaskedall @agingoldseco and see if this is the expected behaviour.

**Comment by swissspidy** [comment] 2022-03-02 17:38
For context, my argument was that this is working as intended:

Users can change the aspect ratio for art direction by double clicking on an image/video. Replacing a video/image either using Quick Actions or by drag & drop should not change the desired aspect ratio.

If replacing a landscape video with a portrait one, the aspect ratio can be changed using double click:

https://user-images.githubusercontent.com/841956/156416737-20b2c0d7-0478-40de-8e5a-aa7e3d3e0a55.mov

Also not aware of any user reports about this in the forums, which is also an indicator that this is not considered a bug.

Thus I'd say it's a feature and we don't need to do anything :)

**Comment by agingoldseco** [comment] 2022-03-03 17:03
Echoing Pascal, I think this is working as intended as long as the user can still double click and change it as they see fit and the video itself is not warped in any way. They're hopefully used to the double-clicking convention for cropping both images and videos by now, and we risk messing up templates and thoughtfully-created layouts by automatically changing aspect ratios when media is replaced.

**Comment by swissspidy** [comment] 2022-03-03 18:00
Closing this as a wontfix then :)

**Closed as completed by swissspidy** 2022-03-03 18:00 UTC
Labels: Type: Bug, Status: Not Applicable, Group: Media, P2, Elements: Video, Group: Quick Action Menu
