### ISSUE TITLE
Move quick action / canvas action menu move to corner for extra small canvas

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#9813] opened 2021-11-24 19:13 UTC
## Feature Description
Originally reported by @agingoldseco 
> We should also have the quick menus combine and move to the corner if the user makes the canvas extra tiny too, not just super zoomed in

**Comment by miina** [comment] 2021-11-25 09:05
Duplicate of #9808

**Closed as completed by miina** 2021-11-25 09:05 UTC
Labels: Type: Enhancement, Group: Quick Action Menu
