### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'vertical')

### ISSUE THREAD

**Issue by tallapallyn** [swissspidy/web-stories-wp#13071] opened 2023-02-24 02:41 UTC
Add new page (or create new is ok)

    - On a blank page, select Text and choose either Title or Paragraph, and click Add

    - For the text box, select a different Font size
   
    - Move curser to outside of the text box and click anywhere on the blank page
    
    - Result: Something went wrong message appears
Please find below link.

https://www.awesomescreenshot.com/video/15075656?key=79a0c9156022dab827ee4cef47181fcc

**Comment by swissspidy** [comment] 2023-02-24 09:04
I cannot reproduce this on the latest version of the plugin. Which version are you on? I know that we shipped some improvements in this area in the latest version. If the issue occurs with v1.30.0, try using [the `web-stories-dev.zip` build](https://github.com/GoogleForCreators/web-stories-wp/releases/tag/v1.30.0) to have better error stack trace for debugging.

Since you use a heavily customized version of the editor, it might be an issue with your custom implementation.

**Comment by tallapallyn** [comment] 2023-02-24 10:07
Hi Pascal Birchler
I tried latest version also, facing same problem.
Select font size and click on white background.

**Comment by swissspidy** [comment] 2023-02-24 10:28
Ah I see, it happens when immediately clicking on the page after changing the font size.

We'll fix this in our next release.

**Comment by swissspidy** [comment] 2023-02-27 10:21
Fixed by #13073

**Closed as completed by swissspidy** 2023-02-27 10:21 UTC
Labels: Type: Bug, Status: Needs More Info, Elements: Text, Package: Elements
