### ISSUE TITLE
Linear filter not being applied to images on Stories

### ISSUE THREAD

**Issue by adamdunnage** [swissspidy/web-stories-wp#13013] opened 2023-02-09 16:30 UTC
## Bug Description

Stories that have had a linear filter added to an image do not display that filter when previewing from the editor or on the published Story. This has been introduced in the 1.29.0 release as this can't be replicated on previous versions. All other filters seem to work and this only effects the linear filter.

This was first reported by a [user in the support forum](https://wordpress.org/support/topic/after-update-google-web-stories-plugin-today-background-image-filter-not-work/#post-16455953).

**Linear image in the editor:**

![linear-editor](https://user-images.githubusercontent.com/91896826/217876131-e0db40cb-6d75-45f2-bea6-3e85c572c2ff.png)

**Linear image in preview:**

![linear-preview](https://user-images.githubusercontent.com/91896826/217876196-19cc1c08-232e-43c3-8dd8-7f1e6fedfc32.png)

## Steps to Reproduce

1. Create a new Story on version 1.29.0 of the plugin.
2. Add an image.
3. Apply the linear filter to the image.
4. Compare the image in the editor to the preview and published Story.

## Screenshots

See above.

## Additional Context

- Plugin Version: 1.29.0

**Comment by swissspidy** [comment] 2023-02-09 16:40
OK I can see the issue on the QA site but not locally 🤔

**Comment by swissspidy** [comment] 2023-02-09 16:45
The generated CSS should look like this:

```css
background-image: linear-gradient(.5turn,rgba(0,0,0,0) 0%,rgba(0,0,0,.7) 100%
```

But it ends up being:

```css
linear-gradient(.5 turn,rgba(0,0,0,0) 0%,rgba(0,0,0,.7) 100%
```

```diff
-linear-gradient(.5turn,rgba(0,0,0,0) 0%,rgba(0,0,0,.7) 100%
+linear-gradient(.5 turn,rgba(0,0,0,0) 0%,rgba(0,0,0,.7) 100%
```

Notice the space after `.5`

Don't know where that is coming from 🤔  Maybe the PHP-CSS-Parser or the AMP sanitization.

**Comment by swissspidy** [comment] 2023-02-10 12:58
So far unable to reproduce reliably unfortunately. It didn't work on our QA site yesterday, but today all seems fine. On the staging site it still doesn't seem to work though, but not sure why.

**Comment by swissspidy** [comment] 2023-02-10 14:36
I've been able to track this down to `AMP_Style_Sanitizer` on our staging site, where this issue occurs. Does not happen with `'disable_style_processing' => true,`

The issue does not happen for me locally though, makes debugging a bit cumbersome.

@westonruter Is this perhaps an issue you've seen in the past?

**Comment by westonruter** [comment] 2023-02-10 17:44
Processing of the `turn` unit was broken in older versions of php-css-parser but it was fixed in https://github.com/sabberworm/PHP-CSS-Parser/pull/350. This is on `master` as of Dec 28, 2021 but is not in the most recent release which was [8.4.0](https://github.com/sabberworm/PHP-CSS-Parser/releases/tag/8.4.0) on Dec 21, 2021 (note: this is the latest _tag_, not the latest _release_). But you're using the version of `php-css-parser` in the most recent stable version of the AMP plugin, right?

**Comment by westonruter** [comment] 2023-02-10 17:49
Is that CSS correct though? I tried looking at it on a non-AMP page and Chrome DevTools gave me a warning. And I just checked in the [W3C CSS Validator](https://jigsaw.w3.org/css-validator/) with this:

```css
div {
    background-image: linear-gradient(.5turn,rgba(0,0,0,0) 0%,rgba(0,0,0,.7) 100%
}
```

And I got:

![Value Error : background-image Parse Error](https://user-images.githubusercontent.com/134745/218160926-a973bd31-9eeb-4f8a-8539-754d6c1ede02.png)

**Comment by westonruter** [comment] 2023-02-10 17:56
Is there a missing closing parenthesis for the `linear-gradient()` function? If I add that missing `)` then Chrome DevTools no longer gives me a warning:

![image](https://user-images.githubusercontent.com/134745/218162156-48963226-c789-4644-b360-3dcd5b7237e1.png)

And I see the gradient show up on an AMP page (and non-AMP page) as expected.

**Comment by swissspidy** [comment] 2023-02-10 18:13
I don't think it's an issue with the PHP-CSS-Parser version, because the exact same version of the plugin seems to run fine on one site but not the other. No AMP plugin installed.

Regarding the validity, I simply forgot to paste the closing `)`.

The problem is the `.5 turn` vs `.5turn`.

**Comment by swissspidy** [comment] 2023-02-10 18:41
> But you're using the version of php-css-parser in the most recent stable version of the AMP plugin, right?

Yes, we use whatever the AMP plugin uses. Looks like it contains that fix because of composer patches.

**Comment by westonruter** [comment] 2023-02-10 19:12
Could it be that you have another plugin that also bundles php-css-parser, but an older version that lacks the fix?

**Comment by swissspidy** [comment] 2023-02-10 19:53
It happens with no other active plugins. Plus we use PHP-Scoper anyway, so other versions of that library shouldn't matter.

But now that you mentioned the specific PR and me mentioning the patches, I recall removing our own composer patches in #12904. Turns out that disabled the AMP plugin's patches too 🤦 

For some reason my local install did still have the patches, which is why I didn't notice this at first.

I just reverted that change in 5b6632149c92032b28a58a27ab98c0d54a75323e and now it seems to work on our staging site as well.

Time for the weekend 🙃 

----

@adamdunnage in short, this should be fixed in our next release

**Closed as completed by swissspidy** 2023-02-10 19:53 UTC
Labels: Type: Bug, Status: Needs More Info, PHP, AMP Output, Group: Style Panel, Type: Support

**Comment by swissspidy** [comment] 2023-02-26 21:03
The patch is now definitely in our latest release, see https://plugins.svn.wordpress.org/web-stories/tags/1.30.0/third-party/vendor/sabberworm/php-css-parser/src/Value/Size.php

Yet we're getting [reports](https://wordpress.org/support/topic/linear-filter-still-not-working-in-latest-version-1-30/) that this issue is still happening, see https://marleysmenu.com/web-stories/fluffy-and-crispy-brown-sugar-pancakes/ for an example with broken `turn` unit.
