### ISSUE TITLE
Firefox: Layers Panel Icons Cut Off

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#9704] opened 2021-11-12 17:36 UTC
Found this while fixing the circle icon to not be cut off (#9559). In firefox the shapes are overflowing a bit in their box and the clip paths are getting cut off. Only in Firefox. Only in the layers panel, not actually impacting usage or the shapes panel. 

![Screen Shot 2021-11-12 at 10.34.16 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/f0bd9926-8663-4df0-807c-142307eb026b)

**Comment by swissspidy** [comment] 2021-11-12 17:50
Duplicate of #9559?

**Comment by BrittanyIRL** [comment] 2021-11-12 19:09
> Duplicate of #9559?

nope! working on 9559 is where i found this. 

In firefox all of the shapes layer icons are overflowing and stretched a little and therefore cut off, whereas the issue with the circle icon alone was that the path was too close to the edge so there's like .5px missing on 2 sides - so that's just updating a path. This is something to do with how the clippath + the styles applied are working in firefox vs chrome, because everything is fine in chrome. So, 2 separate issues.

**Comment by BrookeGraham** [comment] 2021-11-23 18:15
In addition, the clip-path generated for the shapes icon is wonky in Safari.
<img width="359" alt="Screen Shot 2021-11-23 at 11 14 46 AM" src="https://user-images.githubusercontent.com/1820266/143081281-66088070-964c-49aa-a841-30995f24a2c3.png">

**Comment by BrittanyIRL** [comment] 2021-11-23 21:36
Good note, so there's room for improvement in safari and firefox - this means that those browsers are doing something different to display these than Chrome is in this specific case of how the elements are presented in the layers panel (since everything is fine on the shapes panel)

**Closed as completed** 2021-12-15 22:16 UTC
Labels: Type: Bug, Group: Style Panel
