### ISSUE TITLE
Unresponsive with third party integration (Next.js)

### ISSUE THREAD

**Issue by sayamalvi** [swissspidy/web-stories-wp#13593] opened 2024-02-22 12:35 UTC
I am integrating web stories with nextjs and its working fine. Its just not responsive for mobile or tablet screens. There are no guidelines in the documentation as well. Any help will be appreciated.

**Comment by swissspidy** [comment] 2024-02-22 13:13
The Web Stories editor is first and foremost a desktop editor. We only have very limited support for mobile and tablet, so yeah it's not responsive by design and there are currently no plans on expanding that anytime soon. See #11486 and #1686 where this has been raised previously.

While we acknowledge your feature request, I am closing this issue simply for organizational purposes.

**Closed as not planned by swissspidy** 2024-02-22 13:13 UTC
Labels: Type: Enhancement
