### ISSUE TITLE
Error in ffmpeg after video insertion

### ISSUE THREAD

**Issue by westonruter** [swissspidy/web-stories-wp#13128] opened 2023-03-13 21:35 UTC
## Bug Description

After uploading a video and inserting it into a page, I saw the optimizing video snackbar notification. Shortly thereafter, however, I got an error from ffmpeg:

![Screenshot 2023-03-10 15 50 30](https://user-images.githubusercontent.com/134745/224837037-f5284f94-13cd-4d90-afce-a3b92bafe745.png)

This happened at least twice with the following videos:

1. https://weston.ruter.net/wp-content/uploads/2023/03/PXL_20230308_014032123-1.mp4
1. https://weston.ruter.net/wp-content/uploads/2023/03/PXL_20230308_013525772_2-1.mp4
1. https://weston.ruter.net/wp-content/uploads/2023/03/PXL_20230308_013121696-1.mp4

It seemed to work upon a second attempt, however.

## Expected Behaviour

No error from ffmpeg.

## Steps to Reproduce

1. Upload video
2. Insert into post
3. Wait for message regarding optimizing video

## Additional Context

- Plugin Version: 1.30.0
- WordPress Version: 6.1.1
- Operating System: ChromeOS
- Browser: Chrome

**Comment by swissspidy** [comment] 2023-03-13 22:23
Does it happen when directly uploading a video to the editor via drag & drop.

If you install the [1.30.0 development build](https://github.com/GoogleForCreators/web-stories-wp/releases/download/v1.30.0/web-stories-dev.zip) you should see additional logging from FFmpeg that may help pinpoint the issue.

But having recently ran into a similar issue elsewhere, I'd guess the issue is with the `fetchFile()` util provided by ffmpeg.wasm. Replacing it with our own `fetchRemoteFile` util should resolve it.

I'll try to take a closer look tomorrow.

**Comment by westonruter** [comment] 2023-03-13 22:27
I didn't use drag & drop. I opened the media library, selected the video to upload, and then I inserted it.

**Comment by westonruter** [comment] 2023-03-15 21:22
Thanks for that. I was not able to reproduce the issue with that build.

**Comment by westonruter** [comment] 2023-03-15 21:31
I did see something else which doesn't appear to be related:

One `POST` request to `/wp-json/web-stories/v1/media/18462/?_locale=user` failed with a 500 error:

```json
{"code":"rest_meta_database_error","message":"Could not update the meta value of web_stories_optimized_id in database.","data":{"key":"web_stories_optimized_id","status":500}}
```

But other such requests succeeded. I didn't see the snackbar notification in response to that error.

**Comment by swissspidy** [comment] 2023-03-15 23:18
Interesting. Not sure why WP wouldn‘t be able to update the db there, maybe a race condition or corrupt data. But this shouldn‘t cause a snackbar notification.

**Comment by swissspidy** [comment] 2023-03-22 14:29
Closing for now since #13133 got merged

**Closed as completed by swissspidy** 2023-03-22 14:29 UTC
Labels: Type: Bug, Status: Needs More Info, Group: Video Optimization
