### ISSUE TITLE
Users are unable to view more than 38 layers in the layers panel

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11571] opened 2022-05-25 20:18 UTC
## Bug Description

User reports that after creating more than 36 layers in a story page, the editor will permit additional layers to be created, but the user is unable to view or edit these additional layers in the layer panel without deleting layers until they appear in the layers panel

![Screenshot 2022-05-25 at 10.44.06.png](https://images.zenhubusercontent.com/5e8b274ee5c3c7dfddf4be62/6221fe85-8be6-4fe1-8396-41538c36ffec)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment] 2022-05-30 13:17
Duplicate of #11572

**Closed as completed by swissspidy** 2022-05-30 13:17 UTC
Labels: Type: Bug, Status: Duplicate, Group: Canvas
