### ISSUE TITLE
Unnecessary scrollbar in saved text styles - Safari

### ISSUE THREAD

**Issue by bmattb** [swissspidy/web-stories-wp#11038] opened 2022-03-23 02:16 UTC
## Bug Description

Originally reported by @spacedmonkey 
Safari bug. See scrollbar on no styled saved. 
<img width="413" alt="image10" src="https://user-images.githubusercontent.com/58738530/159610485-d6434bd3-4604-4048-b6fc-c3b145f750b3.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment] 2023-02-23 09:37
Duplicate of #11979

**Closed as not planned by swissspidy** 2023-02-23 09:37 UTC
Labels: Type: Bug, Group: Saved Styles
