### ISSUE TITLE
Color Picker isn't opening or applying sample color from eyedropper

### ISSUE THREAD

**Issue by LuckynaSan** [swissspidy/web-stories-wp#12681] opened 2022-11-14 14:42 UTC
## Bug Description

A user has reported the color selected from sample color or eyedropper does not apply to the element. Additionally, the color picker is not opening intermittently. Here is the recording of the issue: 
https://www.loom.com/share/c8a3513f766043d59d35f67fd7571a8b

## Expected Behaviour

The color picker should open on click and the color selected should be applied to the element.

## Steps to Reproduce

1. Add page background color
2. Insert an element
3. Open color picker from style tab 
4. Select sample color and pick a color. Note color does not apply to element. 
5. in Style Tab, open color picker once more and notice the menu does not open.

## Additional Context

support topic: https://wordpress.org/support/topic/color-picker-not-working-7/

- Plugin Version: 1.27.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome, Firefox

**Comment by swissspidy** [comment] 2022-11-14 15:05
@LuckynaSan Duplicate of #12560?

**Comment by swissspidy** [comment] 2022-11-14 17:09
Let's treat that other ticket as the general "eyedropper is not working" ticket

**Closed as not planned by swissspidy** 2022-11-14 17:09 UTC
Labels: Type: Bug, Status: Duplicate, Group: Style Panel
