### ISSUE TITLE
Story Editor Karma Timeout Failure 

### ISSUE THREAD

**Issue by BrittanyIRL** [swissspidy/web-stories-wp#10052] opened 2021-12-22 19:25 UTC
## Bug Description

All of the Karma tests are failing due to a timeout issue! 

This started last week. I believe the issue stems from commit `c6798df96` to main - PR #9952. I've documented my findings here: https://github.com/google/web-stories-wp/pull/10045 as @BrookeGraham  and I attempted to debug while most of the team's out on holiday PTO. At this point, it needs fresh perspective. 

## Expected Behaviour

Karma tests should run and ideally pass, but at least get them running again :) 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment] 2021-12-22 20:59
Ooh the font provider is the culprot? 👀😬

The fonts response should already be mocked there though 🤔

**Comment by BrittanyIRL** [comment] 2021-12-22 22:28
> 


> Ooh the font provider is the culprit? 👀😬

This is what it seems like? We can talk through it more after the holidays. Wanted to document what I found before I took off.

**Comment by amovar18** [comment] 2021-12-29 10:53
If I may add I think this issue started before this PR(#9952) it started in PR #9953 after which the karma test failed I tried running a commit which was merged right before this PR it was a dependabot bump of `react-virtual` the karma test succeeded in that case.

**Comment by samwhale** [comment] 2021-12-29 12:23
> If I may add I think this issue started before this PR(#9952) it started in PR #9953 after which the karma test failed I tried running a commit which was merged right before this PR it was a dependabot bump of `react-virtual` the karma test succeeded in that case.

Oh! Wondering if we need to add some mocks for [updateBlurHash/getBlurHashFromImage](https://github.com/google/web-stories-wp/pull/9953/files#diff-963a275ee556094af0498bc388d48a054bb4a1dacf0aedd2cb05dd5ff0c0a5aeR80-R108) in the karma fixture 🤔.

**Comment by samwhale** [comment] 2021-12-29 13:08
Made a quick PR to test if mocking the `useDetectBlurHash` hook will fix the problem 😄

**Comment by amovar18** [comment] 2021-12-29 17:35
I guess my discovery regarding the cause of failure worked.

**Comment by swissspidy** [comment] 2022-01-04 13:22
Things seem to look better now after merging #10016, there's now just some unhandled promise rejection error in the eyedropper causing Karma tests to fail (but unfortunately display as passed):

https://github.com/google/web-stories-wp/runs/4702243393?check_suite_focus=true#step:6:3424

There should definitely be a `catch` here:

https://github.com/google/web-stories-wp/blob/86af98c8e9784e9a0c1aac60c2d162cdbac668f9/packages/story-editor/src/components/eyedropper/index.js#L83-L94

**Closed as completed** 2022-01-11 20:14 UTC
Labels: Type: Bug, P1
